name: Build and Deploy

on:
  push:
    branches:
        - master
  pull_request:
    branches:
        - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./Backend
        run: npm install - f

      - name: Create .env file
        working-directory: ./Backend
        run: |
          touch .env
          echo "PORT=8000" >> .env

      - name: Run test
        working-directory: ./Backend
        run: |
          npm test
          if [ $? -ne 0 ]; then
            echo "Tests failed, exiting."
            exit 1
          fi

      - name: Build Docker Image for Server
        working-directory: ./Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/music_labs_backend_v6:latest .

      - name: Build Docker Image for Frontend
        working-directory: ./Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/music_labs_frontend_v7:latest .        

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to DockerHub
        working-directory: ./Backend
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/music_labs_backend_v6:latest
          

      - name: Push Image to DockerHub
        working-directory: ./Frontend
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/music_labs_frontend_v7:latest

      - name: Deploy Backend to Render
        working-directory: ./Backend
        run: |
          curl ${{ secrets.RENDER_DEPLOY_BACKEND }}